version: '3.1'

volumes:
  face_db_data:

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ../plugin-name:/var/www/html/wp-content/plugins/plugin-name/

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ../.mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
        PMA_HOST: mysql

  facerecognition:
    image: hackers/faces
    command: ./wait.sh -s db:5432 -- ./run.sh python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    ports:
      - 80:8000

  db:
    image: postgres
    volumes:
      - face_db_data:/var/lib/postgresql/data